export const CODES = [
  {
    Name: 'Afghanistan',
    Alpha_2: 'AF',
    Alpha_3: 'AFG',
    Numeric: '004',
  },
  {
    Name: 'Åland Islands',
    Alpha_2: 'AX',
    Alpha_3: 'ALA',
    Numeric: '248',
  },
  {
    Name: 'Albania',
    Alpha_2: 'AL',
    Alpha_3: 'ALB',
    Numeric: '008',
  },
  {
    Name: 'Algeria',
    Alpha_2: 'DZ',
    Alpha_3: 'DZA',
    Numeric: '012',
  },
  {
    Name: 'American Samoa',
    Alpha_2: 'AS',
    Alpha_3: 'ASM',
    Numeric: '016',
  },
  {
    Name: 'Andorra',
    Alpha_2: 'AD',
    Alpha_3: 'AND',
    Numeric: '020',
  },
  {
    Name: 'Angola',
    Alpha_2: 'AO',
    Alpha_3: 'AGO',
    Numeric: '024',
  },
  {
    Name: 'Anguilla',
    Alpha_2: 'AI',
    Alpha_3: 'AIA',
    Numeric: '660',
  },
  {
    Name: 'Antarctica',
    Alpha_2: 'AQ',
    Alpha_3: 'ATA',
    Numeric: '010',
  },
  {
    Name: 'Antigua and Barbuda',
    Alpha_2: 'AG',
    Alpha_3: 'ATG',
    Numeric: '028',
  },
  {
    Name: 'Argentina',
    Alpha_2: 'AR',
    Alpha_3: 'ARG',
    Numeric: '032',
  },
  {
    Name: 'Armenia',
    Alpha_2: 'AM',
    Alpha_3: 'ARM',
    Numeric: '051',
  },
  {
    Name: 'Aruba',
    Alpha_2: 'AW',
    Alpha_3: 'ABW',
    Numeric: '533',
  },
  {
    Name: 'Australia',
    Alpha_2: 'AU',
    Alpha_3: 'AUS',
    Numeric: '036',
  },
  {
    Name: 'Austria',
    Alpha_2: 'AT',
    Alpha_3: 'AUT',
    Numeric: '040',
  },
  {
    Name: 'Azerbaijan',
    Alpha_2: 'AZ',
    Alpha_3: 'AZE',
    Numeric: '031',
  },
  {
    Name: 'Bahamas',
    Alpha_2: 'BS',
    Alpha_3: 'BHS',
    Numeric: '044',
  },
  {
    Name: 'Bahrain',
    Alpha_2: 'BH',
    Alpha_3: 'BHR',
    Numeric: '048',
  },
  {
    Name: 'Bangladesh',
    Alpha_2: 'BD',
    Alpha_3: 'BGD',
    Numeric: '050',
  },
  {
    Name: 'Barbados',
    Alpha_2: 'BB',
    Alpha_3: 'BRB',
    Numeric: '052',
  },
  {
    Name: 'Belarus',
    Alpha_2: 'BY',
    Alpha_3: 'BLR',
    Numeric: '112',
  },
  {
    Name: 'Belgium',
    Alpha_2: 'BE',
    Alpha_3: 'BEL',
    Numeric: '056',
  },
  {
    Name: 'Belize',
    Alpha_2: 'BZ',
    Alpha_3: 'BLZ',
    Numeric: '084',
  },
  {
    Name: 'Benin',
    Alpha_2: 'BJ',
    Alpha_3: 'BEN',
    Numeric: '204',
  },
  {
    Name: 'Bermuda',
    Alpha_2: 'BM',
    Alpha_3: 'BMU',
    Numeric: '060',
  },
  {
    Name: 'Bhutan',
    Alpha_2: 'BT',
    Alpha_3: 'BTN',
    Numeric: '064',
  },
  {
    Name: 'Bolivia (Plurinational State of)',
    Alpha_2: 'BO',
    Alpha_3: 'BOL',
    Numeric: '068',
  },
  {
    Name: 'Bonaire, Sint Eustatius and Saba',
    Alpha_2: 'BQ',
    Alpha_3: 'BES',
    Numeric: '535',
  },
  {
    Name: 'Bosnia and Herzegovina',
    Alpha_2: 'BA',
    Alpha_3: 'BIH',
    Numeric: '070',
  },
  {
    Name: 'Botswana',
    Alpha_2: 'BW',
    Alpha_3: 'BWA',
    Numeric: '072',
  },
  {
    Name: 'Bouvet Island',
    Alpha_2: 'BV',
    Alpha_3: 'BVT',
    Numeric: '074',
  },
  {
    Name: 'Brazil',
    Alpha_2: 'BR',
    Alpha_3: 'BRA',
    Numeric: '076',
  },
  {
    Name: 'British Indian Ocean Territory',
    Alpha_2: 'IO',
    Alpha_3: 'IOT',
    Numeric: '086',
  },
  {
    Name: 'Brunei Darussalam',
    Alpha_2: 'BN',
    Alpha_3: 'BRN',
    Numeric: '096',
  },
  {
    Name: 'Bulgaria',
    Alpha_2: 'BG',
    Alpha_3: 'BGR',
    Numeric: '100',
  },
  {
    Name: 'Burkina Faso',
    Alpha_2: 'BF',
    Alpha_3: 'BFA',
    Numeric: '854',
  },
  {
    Name: 'Burundi',
    Alpha_2: 'BI',
    Alpha_3: 'BDI',
    Numeric: '108',
  },
  {
    Name: 'Cabo Verde',
    Alpha_2: 'CV',
    Alpha_3: 'CPV',
    Numeric: '132',
  },
  {
    Name: 'Cambodia',
    Alpha_2: 'KH',
    Alpha_3: 'KHM',
    Numeric: '116',
  },
  {
    Name: 'Cameroon',
    Alpha_2: 'CM',
    Alpha_3: 'CMR',
    Numeric: '120',
  },
  {
    Name: 'Canada',
    Alpha_2: 'CA',
    Alpha_3: 'CAN',
    Numeric: '124',
  },
  {
    Name: 'Cayman Islands',
    Alpha_2: 'KY',
    Alpha_3: 'CYM',
    Numeric: '136',
  },
  {
    Name: 'Central African Republic',
    Alpha_2: 'CF',
    Alpha_3: 'CAF',
    Numeric: '140',
  },
  {
    Name: 'Chad',
    Alpha_2: 'TD',
    Alpha_3: 'TCD',
    Numeric: '148',
  },
  {
    Name: 'Chile',
    Alpha_2: 'CL',
    Alpha_3: 'CHL',
    Numeric: '152',
  },
  {
    Name: 'China',
    Alpha_2: 'CN',
    Alpha_3: 'CHN',
    Numeric: '156',
  },
  {
    Name: 'Christmas Island',
    Alpha_2: 'CX',
    Alpha_3: 'CXR',
    Numeric: '162',
  },
  {
    Name: 'Cocos (Keeling) Islands',
    Alpha_2: 'CC',
    Alpha_3: 'CCK',
    Numeric: '166',
  },
  {
    Name: 'Colombia',
    Alpha_2: 'CO',
    Alpha_3: 'COL',
    Numeric: '170',
  },
  {
    Name: 'Comoros',
    Alpha_2: 'KM',
    Alpha_3: 'COM',
    Numeric: '174',
  },
  {
    Name: 'Congo',
    Alpha_2: 'CG',
    Alpha_3: 'COG',
    Numeric: '178',
  },
  {
    Name: 'Congo, Democratic Republic of the',
    Alpha_2: 'CD',
    Alpha_3: 'COD',
    Numeric: '180',
  },
  {
    Name: 'Cook Islands',
    Alpha_2: 'CK',
    Alpha_3: 'COK',
    Numeric: '184',
  },
  {
    Name: 'Costa Rica',
    Alpha_2: 'CR',
    Alpha_3: 'CRI',
    Numeric: '188',
  },
  {
    Name: "Côte d'Ivoire",
    Alpha_2: 'CI',
    Alpha_3: 'CIV',
    Numeric: '384',
  },
  {
    Name: 'Croatia',
    Alpha_2: 'HR',
    Alpha_3: 'HRV',
    Numeric: '191',
  },
  {
    Name: 'Cuba',
    Alpha_2: 'CU',
    Alpha_3: 'CUB',
    Numeric: '192',
  },
  {
    Name: 'Curaçao',
    Alpha_2: 'CW',
    Alpha_3: 'CUW',
    Numeric: '531',
  },
  {
    Name: 'Cyprus',
    Alpha_2: 'CY',
    Alpha_3: 'CYP',
    Numeric: '196',
  },
  {
    Name: 'Czechia',
    Alpha_2: 'CZ',
    Alpha_3: 'CZE',
    Numeric: '203',
  },
  {
    Name: 'Denmark',
    Alpha_2: 'DK',
    Alpha_3: 'DNK',
    Numeric: '208',
  },
  {
    Name: 'Djibouti',
    Alpha_2: 'DJ',
    Alpha_3: 'DJI',
    Numeric: '262',
  },
  {
    Name: 'Dominica',
    Alpha_2: 'DM',
    Alpha_3: 'DMA',
    Numeric: '212',
  },
  {
    Name: 'Dominican Republic',
    Alpha_2: 'DO',
    Alpha_3: 'DOM',
    Numeric: '214',
  },
  {
    Name: 'Ecuador',
    Alpha_2: 'EC',
    Alpha_3: 'ECU',
    Numeric: '218',
  },
  {
    Name: 'Egypt',
    Alpha_2: 'EG',
    Alpha_3: 'EGY',
    Numeric: '818',
  },
  {
    Name: 'El Salvador',
    Alpha_2: 'SV',
    Alpha_3: 'SLV',
    Numeric: '222',
  },
  {
    Name: 'Equatorial Guinea',
    Alpha_2: 'GQ',
    Alpha_3: 'GNQ',
    Numeric: '226',
  },
  {
    Name: 'Eritrea',
    Alpha_2: 'ER',
    Alpha_3: 'ERI',
    Numeric: '232',
  },
  {
    Name: 'Estonia',
    Alpha_2: 'EE',
    Alpha_3: 'EST',
    Numeric: '233',
  },
  {
    Name: 'Eswatini',
    Alpha_2: 'SZ',
    Alpha_3: 'SWZ',
    Numeric: '748',
  },
  {
    Name: 'Ethiopia',
    Alpha_2: 'ET',
    Alpha_3: 'ETH',
    Numeric: '231',
  },
  {
    Name: 'Falkland Islands (Malvinas)',
    Alpha_2: 'FK',
    Alpha_3: 'FLK',
    Numeric: '238',
  },
  {
    Name: 'Faroe Islands',
    Alpha_2: 'FO',
    Alpha_3: 'FRO',
    Numeric: '234',
  },
  {
    Name: 'Fiji',
    Alpha_2: 'FJ',
    Alpha_3: 'FJI',
    Numeric: '242',
  },
  {
    Name: 'Finland',
    Alpha_2: 'FI',
    Alpha_3: 'FIN',
    Numeric: '246',
  },
  {
    Name: 'France',
    Alpha_2: 'FR',
    Alpha_3: 'FRA',
    Numeric: '250',
  },
  {
    Name: 'French Guiana',
    Alpha_2: 'GF',
    Alpha_3: 'GUF',
    Numeric: '254',
  },
  {
    Name: 'French Polynesia',
    Alpha_2: 'PF',
    Alpha_3: 'PYF',
    Numeric: '258',
  },
  {
    Name: 'French Southern Territories',
    Alpha_2: 'TF',
    Alpha_3: 'ATF',
    Numeric: '260',
  },
  {
    Name: 'Gabon',
    Alpha_2: 'GA',
    Alpha_3: 'GAB',
    Numeric: '266',
  },
  {
    Name: 'Gambia',
    Alpha_2: 'GM',
    Alpha_3: 'GMB',
    Numeric: '270',
  },
  {
    Name: 'Georgia',
    Alpha_2: 'GE',
    Alpha_3: 'GEO',
    Numeric: '268',
  },
  {
    Name: 'Germany',
    Alpha_2: 'DE',
    Alpha_3: 'DEU',
    Numeric: '276',
  },
  {
    Name: 'Ghana',
    Alpha_2: 'GH',
    Alpha_3: 'GHA',
    Numeric: '288',
  },
  {
    Name: 'Gibraltar',
    Alpha_2: 'GI',
    Alpha_3: 'GIB',
    Numeric: '292',
  },
  {
    Name: 'Greece',
    Alpha_2: 'GR',
    Alpha_3: 'GRC',
    Numeric: '300',
  },
  {
    Name: 'Greenland',
    Alpha_2: 'GL',
    Alpha_3: 'GRL',
    Numeric: '304',
  },
  {
    Name: 'Grenada',
    Alpha_2: 'GD',
    Alpha_3: 'GRD',
    Numeric: '308',
  },
  {
    Name: 'Guadeloupe',
    Alpha_2: 'GP',
    Alpha_3: 'GLP',
    Numeric: '312',
  },
  {
    Name: 'Guam',
    Alpha_2: 'GU',
    Alpha_3: 'GUM',
    Numeric: '316',
  },
  {
    Name: 'Guatemala',
    Alpha_2: 'GT',
    Alpha_3: 'GTM',
    Numeric: '320',
  },
  {
    Name: 'Guernsey',
    Alpha_2: 'GG',
    Alpha_3: 'GGY',
    Numeric: '831',
  },
  {
    Name: 'Guinea',
    Alpha_2: 'GN',
    Alpha_3: 'GIN',
    Numeric: '324',
  },
  {
    Name: 'Guinea-Bissau',
    Alpha_2: 'GW',
    Alpha_3: 'GNB',
    Numeric: '624',
  },
  {
    Name: 'Guyana',
    Alpha_2: 'GY',
    Alpha_3: 'GUY',
    Numeric: '328',
  },
  {
    Name: 'Haiti',
    Alpha_2: 'HT',
    Alpha_3: 'HTI',
    Numeric: '332',
  },
  {
    Name: 'Heard Island and McDonald Islands',
    Alpha_2: 'HM',
    Alpha_3: 'HMD',
    Numeric: '334',
  },
  {
    Name: 'Holy See',
    Alpha_2: 'VA',
    Alpha_3: 'VAT',
    Numeric: '336',
  },
  {
    Name: 'Honduras',
    Alpha_2: 'HN',
    Alpha_3: 'HND',
    Numeric: '340',
  },
  {
    Name: 'Hong Kong',
    Alpha_2: 'HK',
    Alpha_3: 'HKG',
    Numeric: '344',
  },
  {
    Name: 'Hungary',
    Alpha_2: 'HU',
    Alpha_3: 'HUN',
    Numeric: '348',
  },
  {
    Name: 'Iceland',
    Alpha_2: 'IS',
    Alpha_3: 'ISL',
    Numeric: '352',
  },
  {
    Name: 'India',
    Alpha_2: 'IN',
    Alpha_3: 'IND',
    Numeric: '356',
  },
  {
    Name: 'Indonesia',
    Alpha_2: 'ID',
    Alpha_3: 'IDN',
    Numeric: '360',
  },
  {
    Name: 'Iran (Islamic Republic of)',
    Alpha_2: 'IR',
    Alpha_3: 'IRN',
    Numeric: '364',
  },
  {
    Name: 'Iraq',
    Alpha_2: 'IQ',
    Alpha_3: 'IRQ',
    Numeric: '368',
  },
  {
    Name: 'Ireland',
    Alpha_2: 'IE',
    Alpha_3: 'IRL',
    Numeric: '372',
  },
  {
    Name: 'Isle of Man',
    Alpha_2: 'IM',
    Alpha_3: 'IMN',
    Numeric: '833',
  },
  {
    Name: 'Israel',
    Alpha_2: 'IL',
    Alpha_3: 'ISR',
    Numeric: '376',
  },
  {
    Name: 'Italy',
    Alpha_2: 'IT',
    Alpha_3: 'ITA',
    Numeric: '380',
  },
  {
    Name: 'Jamaica',
    Alpha_2: 'JM',
    Alpha_3: 'JAM',
    Numeric: '388',
  },
  {
    Name: 'Japan',
    Alpha_2: 'JP',
    Alpha_3: 'JPN',
    Numeric: '392',
  },
  {
    Name: 'Jersey',
    Alpha_2: 'JE',
    Alpha_3: 'JEY',
    Numeric: '832',
  },
  {
    Name: 'Jordan',
    Alpha_2: 'JO',
    Alpha_3: 'JOR',
    Numeric: '400',
  },
  {
    Name: 'Kazakhstan',
    Alpha_2: 'KZ',
    Alpha_3: 'KAZ',
    Numeric: '398',
  },
  {
    Name: 'Kenya',
    Alpha_2: 'KE',
    Alpha_3: 'KEN',
    Numeric: '404',
  },
  {
    Name: 'Kiribati',
    Alpha_2: 'KI',
    Alpha_3: 'KIR',
    Numeric: '296',
  },
  {
    Name: "Korea (Democratic People's Republic of)",
    Alpha_2: 'KP',
    Alpha_3: 'PRK',
    Numeric: '408',
  },
  {
    Name: 'Korea, Republic of',
    Alpha_2: 'KR',
    Alpha_3: 'KOR',
    Numeric: '410',
  },
  {
    Name: 'Kuwait',
    Alpha_2: 'KW',
    Alpha_3: 'KWT',
    Numeric: '414',
  },
  {
    Name: 'Kyrgyzstan',
    Alpha_2: 'KG',
    Alpha_3: 'KGZ',
    Numeric: '417',
  },
  {
    Name: "Lao People's Democratic Republic",
    Alpha_2: 'LA',
    Alpha_3: 'LAO',
    Numeric: '418',
  },
  {
    Name: 'Latvia',
    Alpha_2: 'LV',
    Alpha_3: 'LVA',
    Numeric: '428',
  },
  {
    Name: 'Lebanon',
    Alpha_2: 'LB',
    Alpha_3: 'LBN',
    Numeric: '422',
  },
  {
    Name: 'Lesotho',
    Alpha_2: 'LS',
    Alpha_3: 'LSO',
    Numeric: '426',
  },
  {
    Name: 'Liberia',
    Alpha_2: 'LR',
    Alpha_3: 'LBR',
    Numeric: '430',
  },
  {
    Name: 'Libya',
    Alpha_2: 'LY',
    Alpha_3: 'LBY',
    Numeric: '434',
  },
  {
    Name: 'Liechtenstein',
    Alpha_2: 'LI',
    Alpha_3: 'LIE',
    Numeric: '438',
  },
  {
    Name: 'Lithuania',
    Alpha_2: 'LT',
    Alpha_3: 'LTU',
    Numeric: '440',
  },
  {
    Name: 'Luxembourg',
    Alpha_2: 'LU',
    Alpha_3: 'LUX',
    Numeric: '442',
  },
  {
    Name: 'Macao',
    Alpha_2: 'MO',
    Alpha_3: 'MAC',
    Numeric: '446',
  },
  {
    Name: 'Madagascar',
    Alpha_2: 'MG',
    Alpha_3: 'MDG',
    Numeric: '450',
  },
  {
    Name: 'Malawi',
    Alpha_2: 'MW',
    Alpha_3: 'MWI',
    Numeric: '454',
  },
  {
    Name: 'Malaysia',
    Alpha_2: 'MY',
    Alpha_3: 'MYS',
    Numeric: '458',
  },
  {
    Name: 'Maldives',
    Alpha_2: 'MV',
    Alpha_3: 'MDV',
    Numeric: '462',
  },
  {
    Name: 'Mali',
    Alpha_2: 'ML',
    Alpha_3: 'MLI',
    Numeric: '466',
  },
  {
    Name: 'Malta',
    Alpha_2: 'MT',
    Alpha_3: 'MLT',
    Numeric: '470',
  },
  {
    Name: 'Marshall Islands',
    Alpha_2: 'MH',
    Alpha_3: 'MHL',
    Numeric: '584',
  },
  {
    Name: 'Martinique',
    Alpha_2: 'MQ',
    Alpha_3: 'MTQ',
    Numeric: '474',
  },
  {
    Name: 'Mauritania',
    Alpha_2: 'MR',
    Alpha_3: 'MRT',
    Numeric: '478',
  },
  {
    Name: 'Mauritius',
    Alpha_2: 'MU',
    Alpha_3: 'MUS',
    Numeric: '480',
  },
  {
    Name: 'Mayotte',
    Alpha_2: 'YT',
    Alpha_3: 'MYT',
    Numeric: '175',
  },
  {
    Name: 'Mexico',
    Alpha_2: 'MX',
    Alpha_3: 'MEX',
    Numeric: '484',
  },
  {
    Name: 'Micronesia (Federated States of)',
    Alpha_2: 'FM',
    Alpha_3: 'FSM',
    Numeric: '583',
  },
  {
    Name: 'Moldova, Republic of',
    Alpha_2: 'MD',
    Alpha_3: 'MDA',
    Numeric: '498',
  },
  {
    Name: 'Monaco',
    Alpha_2: 'MC',
    Alpha_3: 'MCO',
    Numeric: '492',
  },
  {
    Name: 'Mongolia',
    Alpha_2: 'MN',
    Alpha_3: 'MNG',
    Numeric: '496',
  },
  {
    Name: 'Montenegro',
    Alpha_2: 'ME',
    Alpha_3: 'MNE',
    Numeric: '499',
  },
  {
    Name: 'Montserrat',
    Alpha_2: 'MS',
    Alpha_3: 'MSR',
    Numeric: '500',
  },
  {
    Name: 'Morocco',
    Alpha_2: 'MA',
    Alpha_3: 'MAR',
    Numeric: '504',
  },
  {
    Name: 'Mozambique',
    Alpha_2: 'MZ',
    Alpha_3: 'MOZ',
    Numeric: '508',
  },
  {
    Name: 'Myanmar',
    Alpha_2: 'MM',
    Alpha_3: 'MMR',
    Numeric: '104',
  },
  {
    Name: 'Namibia',
    Alpha_2: 'NA',
    Alpha_3: 'NAM',
    Numeric: '516',
  },
  {
    Name: 'Nauru',
    Alpha_2: 'NR',
    Alpha_3: 'NRU',
    Numeric: '520',
  },
  {
    Name: 'Nepal',
    Alpha_2: 'NP',
    Alpha_3: 'NPL',
    Numeric: '524',
  },
  {
    Name: 'Netherlands',
    Alpha_2: 'NL',
    Alpha_3: 'NLD',
    Numeric: '528',
  },
  {
    Name: 'New Caledonia',
    Alpha_2: 'NC',
    Alpha_3: 'NCL',
    Numeric: '540',
  },
  {
    Name: 'New Zealand',
    Alpha_2: 'NZ',
    Alpha_3: 'NZL',
    Numeric: '554',
  },
  {
    Name: 'Nicaragua',
    Alpha_2: 'NI',
    Alpha_3: 'NIC',
    Numeric: '558',
  },
  {
    Name: 'Niger',
    Alpha_2: 'NE',
    Alpha_3: 'NER',
    Numeric: '562',
  },
  {
    Name: 'Nigeria',
    Alpha_2: 'NG',
    Alpha_3: 'NGA',
    Numeric: '566',
  },
  {
    Name: 'Niue',
    Alpha_2: 'NU',
    Alpha_3: 'NIU',
    Numeric: '570',
  },
  {
    Name: 'Norfolk Island',
    Alpha_2: 'NF',
    Alpha_3: 'NFK',
    Numeric: '574',
  },
  {
    Name: 'North Macedonia',
    Alpha_2: 'MK',
    Alpha_3: 'MKD',
    Numeric: '807',
  },
  {
    Name: 'Northern Mariana Islands',
    Alpha_2: 'MP',
    Alpha_3: 'MNP',
    Numeric: '580',
  },
  {
    Name: 'Norway',
    Alpha_2: 'NO',
    Alpha_3: 'NOR',
    Numeric: '578',
  },
  {
    Name: 'Oman',
    Alpha_2: 'OM',
    Alpha_3: 'OMN',
    Numeric: '512',
  },
  {
    Name: 'Pakistan',
    Alpha_2: 'PK',
    Alpha_3: 'PAK',
    Numeric: '586',
  },
  {
    Name: 'Palau',
    Alpha_2: 'PW',
    Alpha_3: 'PLW',
    Numeric: '585',
  },
  {
    Name: 'Palestine, State of',
    Alpha_2: 'PS',
    Alpha_3: 'PSE',
    Numeric: '275',
  },
  {
    Name: 'Panama',
    Alpha_2: 'PA',
    Alpha_3: 'PAN',
    Numeric: '591',
  },
  {
    Name: 'Papua New Guinea',
    Alpha_2: 'PG',
    Alpha_3: 'PNG',
    Numeric: '598',
  },
  {
    Name: 'Paraguay',
    Alpha_2: 'PY',
    Alpha_3: 'PRY',
    Numeric: '600',
  },
  {
    Name: 'Peru',
    Alpha_2: 'PE',
    Alpha_3: 'PER',
    Numeric: '604',
  },
  {
    Name: 'Philippines',
    Alpha_2: 'PH',
    Alpha_3: 'PHL',
    Numeric: '608',
  },
  {
    Name: 'Pitcairn',
    Alpha_2: 'PN',
    Alpha_3: 'PCN',
    Numeric: '612',
  },
  {
    Name: 'Poland',
    Alpha_2: 'PL',
    Alpha_3: 'POL',
    Numeric: '616',
  },
  {
    Name: 'Portugal',
    Alpha_2: 'PT',
    Alpha_3: 'PRT',
    Numeric: '620',
  },
  {
    Name: 'Puerto Rico',
    Alpha_2: 'PR',
    Alpha_3: 'PRI',
    Numeric: '630',
  },
  {
    Name: 'Qatar',
    Alpha_2: 'QA',
    Alpha_3: 'QAT',
    Numeric: '634',
  },
  {
    Name: 'Réunion',
    Alpha_2: 'RE',
    Alpha_3: 'REU',
    Numeric: '638',
  },
  {
    Name: 'Romania',
    Alpha_2: 'RO',
    Alpha_3: 'ROU',
    Numeric: '642',
  },
  {
    Name: 'Russian Federation',
    Alpha_2: 'RU',
    Alpha_3: 'RUS',
    Numeric: '643',
  },
  {
    Name: 'Rwanda',
    Alpha_2: 'RW',
    Alpha_3: 'RWA',
    Numeric: '646',
  },
  {
    Name: 'Saint Barthélemy',
    Alpha_2: 'BL',
    Alpha_3: 'BLM',
    Numeric: '652',
  },
  {
    Name: 'Saint Helena, Ascension and Tristan da Cunha',
    Alpha_2: 'SH',
    Alpha_3: 'SHN',
    Numeric: '654',
  },
  {
    Name: 'Saint Kitts and Nevis',
    Alpha_2: 'KN',
    Alpha_3: 'KNA',
    Numeric: '659',
  },
  {
    Name: 'Saint Lucia',
    Alpha_2: 'LC',
    Alpha_3: 'LCA',
    Numeric: '662',
  },
  {
    Name: 'Saint Martin (French part)',
    Alpha_2: 'MF',
    Alpha_3: 'MAF',
    Numeric: '663',
  },
  {
    Name: 'Saint Pierre and Miquelon',
    Alpha_2: 'PM',
    Alpha_3: 'SPM',
    Numeric: '666',
  },
  {
    Name: 'Saint Vincent and the Grenadines',
    Alpha_2: 'VC',
    Alpha_3: 'VCT',
    Numeric: '670',
  },
  {
    Name: 'Samoa',
    Alpha_2: 'WS',
    Alpha_3: 'WSM',
    Numeric: '882',
  },
  {
    Name: 'San Marino',
    Alpha_2: 'SM',
    Alpha_3: 'SMR',
    Numeric: '674',
  },
  {
    Name: 'Sao Tome and Principe',
    Alpha_2: 'ST',
    Alpha_3: 'STP',
    Numeric: '678',
  },
  {
    Name: 'Saudi Arabia',
    Alpha_2: 'SA',
    Alpha_3: 'SAU',
    Numeric: '682',
  },
  {
    Name: 'Senegal',
    Alpha_2: 'SN',
    Alpha_3: 'SEN',
    Numeric: '686',
  },
  {
    Name: 'Serbia',
    Alpha_2: 'RS',
    Alpha_3: 'SRB',
    Numeric: '688',
  },
  {
    Name: 'Seychelles',
    Alpha_2: 'SC',
    Alpha_3: 'SYC',
    Numeric: '690',
  },
  {
    Name: 'Sierra Leone',
    Alpha_2: 'SL',
    Alpha_3: 'SLE',
    Numeric: '694',
  },
  {
    Name: 'Singapore',
    Alpha_2: 'SG',
    Alpha_3: 'SGP',
    Numeric: '702',
  },
  {
    Name: 'Sint Maarten (Dutch part)',
    Alpha_2: 'SX',
    Alpha_3: 'SXM',
    Numeric: '534',
  },
  {
    Name: 'Slovakia',
    Alpha_2: 'SK',
    Alpha_3: 'SVK',
    Numeric: '703',
  },
  {
    Name: 'Slovenia',
    Alpha_2: 'SI',
    Alpha_3: 'SVN',
    Numeric: '705',
  },
  {
    Name: 'Solomon Islands',
    Alpha_2: 'SB',
    Alpha_3: 'SLB',
    Numeric: '090',
  },
  {
    Name: 'Somalia',
    Alpha_2: 'SO',
    Alpha_3: 'SOM',
    Numeric: '706',
  },
  {
    Name: 'South Africa',
    Alpha_2: 'ZA',
    Alpha_3: 'ZAF',
    Numeric: '710',
  },
  {
    Name: 'South Georgia and the South Sandwich Islands',
    Alpha_2: 'GS',
    Alpha_3: 'SGS',
    Numeric: '239',
  },
  {
    Name: 'South Sudan',
    Alpha_2: 'SS',
    Alpha_3: 'SSD',
    Numeric: '728',
  },
  {
    Name: 'Spain',
    Alpha_2: 'ES',
    Alpha_3: 'ESP',
    Numeric: '724',
  },
  {
    Name: 'Sri Lanka',
    Alpha_2: 'LK',
    Alpha_3: 'LKA',
    Numeric: '144',
  },
  {
    Name: 'Sudan',
    Alpha_2: 'SD',
    Alpha_3: 'SDN',
    Numeric: '729',
  },
  {
    Name: 'Suriname',
    Alpha_2: 'SR',
    Alpha_3: 'SUR',
    Numeric: '740',
  },
  {
    Name: 'Svalbard and Jan Mayen',
    Alpha_2: 'SJ',
    Alpha_3: 'SJM',
    Numeric: '744',
  },
  {
    Name: 'Sweden',
    Alpha_2: 'SE',
    Alpha_3: 'SWE',
    Numeric: '752',
  },
  {
    Name: 'Switzerland',
    Alpha_2: 'CH',
    Alpha_3: 'CHE',
    Numeric: '756',
  },
  {
    Name: 'Syrian Arab Republic',
    Alpha_2: 'SY',
    Alpha_3: 'SYR',
    Numeric: '760',
  },
  {
    Name: 'Taiwan, Province of China',
    Alpha_2: 'TW',
    Alpha_3: 'TWN',
    Numeric: '158',
  },
  {
    Name: 'Tajikistan',
    Alpha_2: 'TJ',
    Alpha_3: 'TJK',
    Numeric: '762',
  },
  {
    Name: 'Tanzania, United Republic of',
    Alpha_2: 'TZ',
    Alpha_3: 'TZA',
    Numeric: '834',
  },
  {
    Name: 'Thailand',
    Alpha_2: 'TH',
    Alpha_3: 'THA',
    Numeric: '764',
  },
  {
    Name: 'Timor-Leste',
    Alpha_2: 'TL',
    Alpha_3: 'TLS',
    Numeric: '626',
  },
  {
    Name: 'Togo',
    Alpha_2: 'TG',
    Alpha_3: 'TGO',
    Numeric: '768',
  },
  {
    Name: 'Tokelau',
    Alpha_2: 'TK',
    Alpha_3: 'TKL',
    Numeric: '772',
  },
  {
    Name: 'Tonga',
    Alpha_2: 'TO',
    Alpha_3: 'TON',
    Numeric: '776',
  },
  {
    Name: 'Trinidad and Tobago',
    Alpha_2: 'TT',
    Alpha_3: 'TTO',
    Numeric: '780',
  },
  {
    Name: 'Tunisia',
    Alpha_2: 'TN',
    Alpha_3: 'TUN',
    Numeric: '788',
  },
  {
    Name: 'Turkey',
    Alpha_2: 'TR',
    Alpha_3: 'TUR',
    Numeric: '792',
  },
  {
    Name: 'Turkmenistan',
    Alpha_2: 'TM',
    Alpha_3: 'TKM',
    Numeric: '795',
  },
  {
    Name: 'Turks and Caicos Islands',
    Alpha_2: 'TC',
    Alpha_3: 'TCA',
    Numeric: '796',
  },
  {
    Name: 'Tuvalu',
    Alpha_2: 'TV',
    Alpha_3: 'TUV',
    Numeric: '798',
  },
  {
    Name: 'Uganda',
    Alpha_2: 'UG',
    Alpha_3: 'UGA',
    Numeric: '800',
  },
  {
    Name: 'Ukraine',
    Alpha_2: 'UA',
    Alpha_3: 'UKR',
    Numeric: '804',
  },
  {
    Name: 'United Arab Emirates',
    Alpha_2: 'AE',
    Alpha_3: 'ARE',
    Numeric: '784',
  },
  {
    Name: 'United Kingdom of Great Britain and Northern Ireland',
    Alpha_2: 'GB',
    Alpha_3: 'GBR',
    Numeric: '826',
  },
  {
    Name: 'United States of America',
    Alpha_2: 'US',
    Alpha_3: 'USA',
    Numeric: '840',
  },
  {
    Name: 'United States Minor Outlying Islands',
    Alpha_2: 'UM',
    Alpha_3: 'UMI',
    Numeric: '581',
  },
  {
    Name: 'Uruguay',
    Alpha_2: 'UY',
    Alpha_3: 'URY',
    Numeric: '858',
  },
  {
    Name: 'Uzbekistan',
    Alpha_2: 'UZ',
    Alpha_3: 'UZB',
    Numeric: '860',
  },
  {
    Name: 'Vanuatu',
    Alpha_2: 'VU',
    Alpha_3: 'VUT',
    Numeric: '548',
  },
  {
    Name: 'Venezuela (Bolivarian Republic of)',
    Alpha_2: 'VE',
    Alpha_3: 'VEN',
    Numeric: '862',
  },
  {
    Name: 'Viet Nam',
    Alpha_2: 'VN',
    Alpha_3: 'VNM',
    Numeric: '704',
  },
  {
    Name: 'Virgin Islands (British)',
    Alpha_2: 'VG',
    Alpha_3: 'VGB',
    Numeric: '092',
  },
  {
    Name: 'Virgin Islands (U.S.)',
    Alpha_2: 'VI',
    Alpha_3: 'VIR',
    Numeric: '850',
  },
  {
    Name: 'Wallis and Futuna',
    Alpha_2: 'WF',
    Alpha_3: 'WLF',
    Numeric: '876',
  },
  {
    Name: 'Western Sahara',
    Alpha_2: 'EH',
    Alpha_3: 'ESH',
    Numeric: '732',
  },
  {
    Name: 'Yemen',
    Alpha_2: 'YE',
    Alpha_3: 'YEM',
    Numeric: '887',
  },
  {
    Name: 'Zambia',
    Alpha_2: 'ZM',
    Alpha_3: 'ZMB',
    Numeric: '894',
  },
  {
    Name: 'Zimbabwe',
    Alpha_2: 'ZW',
    Alpha_3: 'ZWE',
    Numeric: '716',
  },
]
